---
title: "Lab 06 - Functions and iterations"
author: "CAMERON FISHER"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
View(diamonds)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = "depth",
    length_mm = "x",
    width_mm = "y",
    depth_mm = "z",
    table_pct = "table"
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

diamonds %>% ggplot(mapping = aes(x = clarity, fill = color)) + geom_bar() + labs(title = "Number of Diamonds per clarity", subtitle = "Filled by colour grade", y = "Frequency", x = "Clarity grade")

diamonds %>% group_by(cut) %>% summarise(mean_price = mean(price)) %>% arrange(mean_price)

diamonds %>% group_by(carat) %>% summarise(mean_table = mean(table_pct)) %>% ggplot(mapping = aes(x = carat, y = mean_table)) + geom_line()

diamonds %>% group_by(carat) %>% summarise(mean_price = mean(price)) %>% ggplot(mapping = aes(x = carat, y = mean_price)) + geom_point() + geom_smooth()

```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?

diamonds %>% summarise(mean_table = mean(table_mm))




# table_mm arithmetic mean within each clarity category


diamonds %>% group_by(clarity) %>% summarise(mean_table = mean(table_mm)) %>% arrange(mean_table)



```

_On average the table size increases as the clarity of the diamonds increase, so there is a negative relationship between the two variable._

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command

gmean <- function(x) {
  exp(mean(log(x)))
}

diamonds %>% summarise(gmean_price = gmean(price)) #test example


```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples

as.numeric(test_data)

output <- vector("double", length(test_data))

for (i in seq_along(test_data)) {
  output[[i]] <- gmean(test_data[[i]])
}

output

```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
